In [ ]:
HPC 4
!pip install cupy-cuda11x 

   ---------------------------------------- 0.0/70.2 MB ? eta -:--:--
   ---------------------------------------- 0.8/70.2 MB 4.8 MB/s eta 0:00:15
   - -------------------------------------- 1.8/70.2 MB 4.8 MB/s eta 0:00:15
   - -------------------------------------- 2.6/70.2 MB 4.4 MB/s eta 0:00:16
   - -------------------------------------- 3.1/70.2 MB 4.9 MB/s eta 0:00:14
   -- ------------------------------------- 3.9/70.2 MB 3.8 MB/s eta 0:00:18
   -- ------------------------------------- 5.2/70.2 MB 4.6 MB/s eta 0:00:15
   --- ------------------------------------ 6.3/70.2 MB 4.6 MB/s eta 0:00:14
   --- ------------------------------------ 6.3/70.2 MB 4.6 MB/s eta 0:00:14
   ---- ----------------------------------- 7.9/70.2 MB 4.2 MB/s eta 0:00:15
   ---- ----------------------------------- 8.4/70.2 MB 4.4 MB/s eta 0:00:15
   ----- ---------------------------------- 8.9/70.2 MB 4.0 MB/s eta 0:00:16
   ----- ---------------------------------- 9.4/70.2 MB 4.0 MB/s eta 0:00:16
   ---


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
USE_GPU = False

if USE_GPU:
    import cupy as xp
else:
    import numpy as xp

# User Input
N = int(input("Enter size of vector/matrix (N): "))

# Input Vectors
print("Enter elements for Vector A:")
A = xp.array([int(input(f"A[{i}]: ")) for i in range(N)])
print("Enter elements for Vector B:")
B = xp.array([int(input(f"B[{i}]: ")) for i in range(N)])

# Vector Addition
C = A + B

print("\nVector A:", A)
print("Vector B:", B)
print("Addition (A + B):", C)

# Input Matrices
print("\nEnter elements for Matrix D:")
D = xp.zeros((N, N), dtype=int)
for i in range(N):
    for j in range(N):
        D[i, j] = int(input(f"D[{i}][{j}]: "))

print("Enter elements for Matrix E:")
E = xp.zeros((N, N), dtype=int)
for i in range(N):
    for j in range(N):
        E[i, j] = int(input(f"E[{i}][{j}]: "))

# Matrix Multiplication
F = D @ E

print("\nMatrix D:")
print(D)

print("\nMatrix E:")
print(E)

print("\nMultiplication Result (D x E):")
print(F)

Enter elements for Vector A:
Enter elements for Vector B:

Vector A: [1 2 3]
Vector B: [4 5 6]
Addition (A + B): [5 7 9]

Enter elements for Matrix D:
Enter elements for Matrix E:

Matrix D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix E:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Multiplication Result (D x E):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
